### ISSUE TITLE
Support for querying JSON DataTypes 

### ISSUE THREAD

**Issue by itajenglish** [77Vincent/sequelize-easy-query#1]
@77Vincent Is there any way you can add support for querying `JSON DataTypes`?

I tried using the current implementation and received this error `SequelizeDatabaseError: operator does not exist: json ~~ unknown`

**Comment by fr-wentianqi** [comment]
Hi @itajenglish,

Thanks for your suggestion, I will look into it recently.

P.S. The code base of this project is not big actually, it's very welcomed if you can fork and contribute.
